services:
  hebrew-stt:
    image: hwdsl2/whisper-server:latest
    container_name: hebrew-stt
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - whisper-data:/var/lib/whisper
    environment:
      - WHISPER_MODEL=large-v3-turbo
      - WHISPER__LANGUAGE=he
    mem_limit: 4g
    mem_reservation: 2g
    pull_policy: always
volumes:
  whisper-data:
